### PR TITLE
Rename master to main

### LINKED ISSUE #737: Rename master to main
GitHub actions mention `master`, and there may be other files to update.

When PR is ready to be merged, FINOS Staff can take care or renaming the branch and merging the PR

### PR DESCRIPTION
**Pull request by SimonCockx**
Fix #737 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by maoo** [comment]
Please ignore the netlify failures above, they'll be running properly as soon as https://github.com/finos/rune-dsl/pull/740 is merged

**Review by maoo — APPROVED** [review]
LGTM!

**Comment by SimonCockx** [comment]
@maoo Since this branch should become the new default branch, I suppose I shouldn't actually merge this PR?

I don't have permissions to modify settings though. I guess someone from the FINOS staff will have to finish this task.

**Comment by maoo** [comment]
ping help@finos.org with the request and we'll switch it in a matter of minutes

**Pull request closed without merging**
